bootstrap.servers=kafka1.home-lab.test.from.home:9093,kafka2.home-lab.test.from.home:9093
security.protocol=SSL
ssl.truststore.location=/home/user/certs/truststore.jks
ssl.truststore.password=TestStorePassword
ssl.keystore.location=/home/user/certs/client.keystore.jks
ssl.keystore.password=TestStorePassword
ssl.key.password=TestStorePassword
