---
# 1. Generate all certificates locally on the control node
#- name: Generate Certificates
 # import_playbook: gen_cert.yml

# 2. Universal Pre-requisites for all nodes
- name: Global Infrastructure Setup
  hosts: 
    - zookeeper-nodes
  remote_user: ec2-user
  become: true
  tasks:
    - name: Ensure Java and QEMU are ready
      dnf:
        name:
      #    - qemu-guest-agent
          - java-17-amazon-corretto-headless
        state: present


# 3. Zookeeper Deployment
- name: Deploy Secure Zookeeper
  hosts: zookeeper-nodes
  become: true
  pre_tasks:
    - name: Create Zookeeper certificate directory
      file:
        path: /var/lib/zookeeper
        state: directory
        owner: zookeeper
        group: zookeeper
        mode: '0755'

    - name: Push Zookeeper Keystore and Truststore
      copy:
        src: "./files/certs/{{ item.src }}"
        dest: "/var/lib/zookeeper/{{ item.dest }}"
        owner: zookeeper
        group: zookeeper
        mode: '0400'
      loop:
        - src: "{{ inventory_hostname }}.keystore.jks"
          dest: "{{ inventory_hostname }}.keystore.jks"
        - src: "truststore.jks"
          dest: "truststore.jks"

  roles:
    - sleighzy.zookeeper
  post_tasks:
    - name:  Insert Zookeeper Configuration
      template:
        src: zoo.cfg.j2
        dest: /usr/share/zookeeper/conf/zoo.cfg
        owner: zookeeper
        group: zookeeper
        mode: '0644'
    - name: Restart Zookeeper Service
      systemd:
        name: zookeeper
        state: restarted
        enabled: yes
        daemon_reload: yes
