#!/bin/bash

# Point to your config file
CONFIG="/home/user/client.properties"
TOPIC="remote_test_topic"

echo "--- Checking Cluster Status ---"
kafka-topics --bootstrap-server kafka1.home-lab.test.from.home:9093 \
             --command-config $CONFIG --list

echo "--- Sending Message from Remote Host ---"
echo "Remote Message: $(date)" | kafka-console-producer \
             --bootstrap-server kafka1.home-lab.test.from.home:9093 \
             --producer.config $CONFIG \
             --topic $TOPIC

echo "--- Reading back from Remote Host ---"
kafka-console-consumer --bootstrap-server kafka1.home-lab.test.from.home:9093 \
             --consumer.config $CONFIG \
             --topic $TOPIC --from-beginning --max-messages 1
